#!/bin/bash

#
# Before running this script please extract raw system image
# and mount loop image to some mount point. Give that mount point
# parameter for this script.
#
# 1. "simg2img system.img system.raw" (Run inside Mer SDK target)
# 2. "mkdir ~/system"
# 3. "sudo mount -t ext4 -o loop system.raw ~/system"
# 4. "droid-system-device/helpers/copy_system.sh ~/system/system rpm/spec-to-modify.spec"
#

if [ $# -lt 2 ]; then
  echo "Usage: droid-system-device/helpers/$(basename "$0") ~/path/to/system rpm/spec-to-modify.spec"
  exit
fi

SYSTEM_SPARSE="sparse/system"
SYSTEM_MOUNT=$1

modify_spec=$(readlink -f "$2")
post_rules=$(mktemp)

# Add read permission for some binaries under system mount
if [ -f helpers/fixup-permissions.sh ]; then
    source helpers/fixup-permissions.sh
else
    source droid-system-device/helpers/fixup-permissions.sh
fi

# Remove current sparse and create it again
rm -rf "$SYSTEM_SPARSE"
mkdir -p "$SYSTEM_SPARSE"

# Copy content
echo "Copy $SYSTEM_MOUNT/* to $SYSTEM_SPARSE"
rsync -a --exclude="lost+found" "$SYSTEM_MOUNT"/* "$SYSTEM_SPARSE"

pushd "$SYSTEM_MOUNT" 1>/dev/null
find . \( -uid +0 -or -gid +0 \) -and \( -type f -or -type d -or -type s \) -printf "[ -e /system/%P ] && chown %U:%G /system/%P\n" 2>/dev/null | LC_ALL="C" sort > "$post_rules"
popd 1>/dev/null

token="# rest of this file is autogenerated. do not edit"
sed -i "/$token/,\$d" "$modify_spec"
echo "$token" >> "$modify_spec"
echo "%post" >> "$modify_spec"

if [ "$(wc -l < "$post_rules")" -gt 0 ]; then
  echo "Updating $modify_spec"
  cat "$post_rules" >> "$modify_spec"
fi
rm -f "$post_rules"

pushd "$SYSTEM_MOUNT" 1>/dev/null
find . -exec getcap {} + 2>/dev/null | awk '{ print "[ -e /system/"$1" ] && " "setcap", $3, "/system/"$1 }' | LC_COLLATE="C" sort >> "$modify_spec"
popd 1>/dev/null

# Remove generic unused directories and files
if [ -f helpers/remove-unused.sh ]; then
    source helpers/remove-unused.sh
else
    source droid-system-device/helpers/remove-unused.sh
fi

# General patches
echo "Apply general patches:"
source droid-system-device/helpers/general-patches.sh

# Move build.prop and prop.default to proper place if spec file has multiple_rpms definition
if grep -q "%define multiple_rpms 1" "$modify_spec"; then
    if [ -f "$SYSTEM_SPARSE"/build.prop ]; then
        DEVICE=$(grep ro.product.name "$SYSTEM_SPARSE"/build.prop | cut -d '_' -f2)
        mkdir -p "$DEVICE"/system
        mv "$SYSTEM_SPARSE"/build.prop "$DEVICE"/system
        if [ -f "$SYSTEM_SPARSE"/etc/prop.default ]; then
            mkdir -p "$DEVICE"/system/etc
            mv "$SYSTEM_SPARSE"/etc/prop.default "$DEVICE"/system/etc/prop.default
        fi
    fi
fi

# Apply patches if exist
if [ -d patches ]; then
    echo "Apply patches:"
    for p in patches/*; do
        patch -p1 -f -i "$p"
    done
fi
